CREATE DATABASE mydatabase;

show TABLES ;
DESCRIBE mytable;
select * from mytable;

-- what is the total revene generated by male vs female customer --
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM mytable
GROUP BY gender;

-- which customer used a discount but still spent more than average purchase amount ? --

SELECT *
FROM mytable
WHERE discount_applied = "yes"
  AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM mytable
    );
    
-- which are thr top 5 products the highest average review rating?--
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM mytable
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- compare thr average purchase amounts between standard and express shipping --

SELECT shipping_type,
Round(avg(purchase_amount),2)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;
    
-- do subscribed customers spend more ? compare the average spend and total revenue betwwen subsribers and non-subsribers --

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue , avg_spend desc;

-- which 5 product have the highest percentage of purchases with discounts applied ?--
select item_purchased,
round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end) /count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new , returning and loyal based on their total number of previous purchases , and show the count of each segment --
with customer_type as(
select customer_id , previous_purchases,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment 
from mytable
)
select customer_segment ,count(*) as 'numbers of customers'
from customer_type
group by customer_segment;


-- what are the top 3 most purchased products within each category --

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from mytable
group by category,item_purchased
)
select item_rank , category ,item_purchased , total_orders
from item_counts
where item_rank <=3;

-- are customers who are reapet buyers (more than 5 previous purchases) also likey to subribe ?--
select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group ?--

select age_group,
sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;
